apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-spring-app
  labels:
    env: dev
spec:
  replicas: 3
  template: 
    metadata: 
      labels:
        env: dev
    spec:
      containers:
        - image: montud/java-spring-app-demo:latest
          name: spring-app
          ports:
            - containerPort: 8080
          
  selector: 
    matchLabels:
      env: dev
